# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e04c6c41fd29cbe7f47096cf6edde93b195137c14a3096ea4b8cf77268b308c4069e4284669c3948936707951b60b7e96d9ce07a0fe613fa872aeebe58cf40c

test:
  secret_key_base: 0108208a4d3b7d971bb0e8a26aa84a07f5b9eeb547cd020dad6ab49d830047575cac3dd8db0b5b65a971c282f04807ca579cd2e24c2e51276ab5066df42fcfe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
